const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Tiger: 0},
	{Keyboard: 0},
	{Anchor: 0},
	{Score: 0},
	{Solid: 0},
	{Platforms: 0},
	{Klccbackground: 0},
	{Sprite: 0},
	{PLatform3: 0},
	{QUEST: 0},
	{HotAirBalloon: 0},
	{food: 0},
	{Cards: 0},
	{Fade: 0},
	{Tween: 0},
	{Rotate: 0},
	{klcards: 0},
	{Mouse: 0},
	{Text: 0},
	{Text2: 0},
	{Sprite3: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Sine: 0},
	{movingPlatform: 0},
	{TiledBackground4: 0},
	{moveablePlatform2: 0},
	{ENEMY: 0},
	{Audio: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{spawn: 0},
	{TiledBackground8: 0},
	{traveloka: 0},
	{Bullet: 0},
	{Baulder: 0},
	{Sprite7: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{TiledBackground11: 0},
	{TiledBackground12: 0},
	{PLAY: 0},
	{HowtoPLay: 0},
	{Sprite10: 0},
	{TiledBackground13: 0},
	{TiledBackground14: 0},
	{Text3: 0},
	{Sprite11: 0},
	{Wrap: 0},
	{ENEMY2: 0},
	{TiledBackground15: 0},
	{MoveTo: 0},
	{BOSS: 0},
	{groundSamsh: 0},
	{PROJECTILE: 0},
	{TiledBackground16: 0},
	{TiledBackground17: 0},
	{TiledBackground18: 0},
	{BossHealthBar: 0},
	{BossHealthBar2: 0},
	{box1: 0},
	{box2: 0},
	{box3: 0},
	{box4: 0},
	{box5: 0},
	{box6: 0},
	{box7: 0},
	{TiledBackground19: 0},
	{TiledBackground20: 0},
	{TiledBackground21: 0},
	{DancingTiger: 0},
	{Sprite13: 0},
	{Text4: 0},
	{cardClicked: 0},
	{Level: 0},
	{Health: 0},
	{BossHP: 0}
];

self.InstanceType = {
	Tiger: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	Platforms: class extends self.ISpriteInstance {},
	Klccbackground: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PLatform3: class extends self.ISpriteInstance {},
	QUEST: class extends self.ITextInstance {},
	HotAirBalloon: class extends self.ISpriteInstance {},
	food: class extends self.ISpriteInstance {},
	Cards: class extends self.ITextInstance {},
	klcards: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	movingPlatform: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	moveablePlatform2: class extends self.ISpriteInstance {},
	ENEMY: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	spawn: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	traveloka: class extends self.ISpriteInstance {},
	Baulder: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	PLAY: class extends self.ISpriteInstance {},
	HowtoPLay: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	ENEMY2: class extends self.ISpriteInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	BOSS: class extends self.ISpriteInstance {},
	groundSamsh: class extends self.ISpriteInstance {},
	PROJECTILE: class extends self.ISpriteInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	TiledBackground18: class extends self.ITiledBackgroundInstance {},
	BossHealthBar: class extends self.ISpriteInstance {},
	BossHealthBar2: class extends self.ISpriteInstance {},
	box1: class extends self.ISpriteInstance {},
	box2: class extends self.ISpriteInstance {},
	box3: class extends self.ISpriteInstance {},
	box4: class extends self.ISpriteInstance {},
	box5: class extends self.ISpriteInstance {},
	box6: class extends self.ISpriteInstance {},
	box7: class extends self.ISpriteInstance {},
	TiledBackground19: class extends self.ITiledBackgroundInstance {},
	TiledBackground20: class extends self.ITiledBackgroundInstance {},
	TiledBackground21: class extends self.ITiledBackgroundInstance {},
	DancingTiger: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {}
}